# Generated by Django 5.0 on 2023-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Аноним', max_length=50, verbose_name='Автор'),
        ),
    ]
