# Generated by Django 5.0 on 2023-12-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='posts.post'),
        ),
    ]
