# Generated by Django 5.0 on 2023-12-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_grade_status_delete_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grade_status',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_status', models.BooleanField(null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='posts.post')),
            ],
        ),
    ]
