# Generated by Django 5.0 on 2024-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_grade_status_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Гость', max_length=50, verbose_name='Автор'),
        ),
    ]
