# Generated by Django 5.0 on 2024-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
