# Generated by Django 5.0 on 2024-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_grade_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
            preserve_default=False,
        ),
    ]
